twitter:
    consumer:
        key: jmhhdex3iUB9WfGasicO0sfHx
        secret: DSv5D6PezNfRCCKpf5vxTuzYjKbnAo7Koj5DQVjwmzDt8ZUN8L
    token: 15044616-vnLIb78QIyiJzfF1rva6kFjW20umQ8sMR6IoraclU
    token-secret: Fjb0I5dgvrvz9YT0VLiwfAW5KOfekg4nATIfQZvDw46MW