twitter:
    consumer:
        key: JgEDbctgyABqv8mmeO20ypalr
        secret: qeesahZKfjFCnAnUANmKW1K6OeS2Piqg0OcHvEynYkwXpCbdyP
    token: 15044616-1ndZ9HIjO0LOU8pERfkrXJ6EL1EjDYtrziCOrpWWD
    token-secret: 8UPNC6GLNvKiKfuQd6v6rga8DNrFMVBnsNy1Si1zJNx3V